# Generated by Django 5.0.4 on 2024-05-01 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('226dbff8-f29b-43fe-8742-cb7539298805'), editable=False, primary_key=True, serialize=False),
        ),
    ]
