# Generated by Django 5.0.4 on 2024-05-02 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b7a276e8-f290-4f2a-a01c-5bf3e3fa1592'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
