# Generated by Django 5.0.4 on 2024-05-08 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_content_id_alter_content_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('404a6306-1621-4e55-b159-6fa90b46d0e8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
