# Generated by Django 5.0.4 on 2024-05-08 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0515b2af-c00a-42a3-82f6-c6297abfc06c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
