# Generated by Django 5.0.4 on 2024-05-08 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6423581-3beb-43cc-a4f7-2d78f156066e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
