# Generated by Django 5.0.4 on 2024-05-08 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cdb63cb9-40d4-40dc-85f6-3041e62cdd2a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
