# Generated by Django 5.0.4 on 2024-05-01 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29c51cd5-e82c-4c68-9d12-357bf2c43a16'), editable=False, primary_key=True, serialize=False),
        ),
    ]
