# Generated by Django 5.0.4 on 2024-05-02 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0003_alter_studentcourse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3dda8573-57e6-480a-8a5d-6645494c60ab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
