# Generated by Django 5.0.4 on 2024-05-08 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0004_alter_studentcourse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20b019a3-32d5-47d7-9bac-33cb434a7a90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
