# Generated by Django 5.0.4 on 2024-05-08 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0005_alter_studentcourse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43942fc4-ae6b-4eef-bee5-aa98586afcee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
