# Generated by Django 5.0.4 on 2024-05-08 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0006_alter_studentcourse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3aac5f2-2c61-4d26-be91-43576cec2866'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
