# Generated by Django 5.0.4 on 2024-05-01 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('25a06e5c-8f93-4ff4-985b-ca4631493e39'), editable=False, primary_key=True, serialize=False),
        ),
    ]
