# Generated by Django 5.0.4 on 2024-05-01 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51cb8964-3b52-4c22-8d91-4b8a06f2ac84'), editable=False, primary_key=True, serialize=False),
        ),
    ]
