# Generated by Django 5.0.4 on 2024-05-08 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c12b5ddc-e62a-4dc7-8f42-5af7aadc72d5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
