# Generated by Django 5.0.4 on 2024-05-08 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_email_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b2a366a-dcca-4716-b45a-1b9568fe962e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
