# Generated by Django 5.0.4 on 2024-05-08 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ad1d4ee-6da8-4ffc-bb70-b24748e55b7f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
