# Generated by Django 5.0.4 on 2024-05-08 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_id_alter_account_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5b7583b-6edf-45c0-8718-dabba2bb9b16'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
