# Generated by Django 5.0.4 on 2024-05-02 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_end_date_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99952a38-c119-4119-bea2-0674efd649a0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
