# Generated by Django 5.0.4 on 2024-05-08 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e17b44e3-a939-4f36-b6f7-bef425fedfc4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
