# Generated by Django 5.0.4 on 2024-05-08 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_id_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c14bd85-d168-44ec-9e03-6c38a10007f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
