# Generated by Django 5.0.4 on 2024-05-08 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74bcb00d-e5bc-4fa2-9639-419659d0f9f3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
