# Generated by Django 5.0.4 on 2024-05-08 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be5a20fa-c7d5-47d0-8504-a06fae7ac294'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
